# Generated by Django 4.1.6 on 2023-02-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_on',
            field=models.DateField(default='2023-02-18'),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
