# Generated by Django 4.1.6 on 2023-02-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_task_created_by_alter_task_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='task',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
