# Generated by Django 4.1.6 on 2023-02-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_task_created_by_historicaltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Project_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
