# Generated by Django 4.1.6 on 2023-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_alter_task_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
